# Generated by Django 4.2.30 on 2026-04-18 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_name_material_material_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuematerialusage',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='issuematerialusage',
            name='material_type',
        ),
        migrations.AddField(
            model_name='issuematerialusage',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='inventory.material'),
        ),
    ]
