# Generated by Django 4.2.29 on 2026-04-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student/Faculty'), ('admin', 'Admin'), ('supervisor', 'Supervisor')], default='student', max_length=20),
        ),
    ]
