# Generated by Django 4.2.29 on 2026-03-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, unique=True)),
                ('response_time', models.IntegerField(help_text='Response time in hours')),
                ('resolution_time', models.IntegerField(help_text='Resolution time in hours')),
            ],
            options={
                'verbose_name_plural': 'SLAs',
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='ai_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='issue',
            name='deadline_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='duplicate_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='issue',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='is_escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issue',
            name='override_llm',
            field=models.BooleanField(default=False),
        ),
    ]
