# Generated by Django 4.2.29 on 2026-04-16 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_sla_issue_ai_summary_issue_deadline_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, help_text='Original issue this is a duplicate of', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='issues.issue'),
        ),
        migrations.AddField(
            model_name='issue',
            name='embedding',
            field=models.BinaryField(blank=True, help_text='Sentence-transformer embedding stored as bytes', null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
    ]
