# Generated by Django 4.2.30 on 2026-04-18 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issues', '0003_issue_duplicate_of_issue_embedding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_issues', to=settings.AUTH_USER_MODEL),
        ),
    ]
