# Generated by Django 4.2.30 on 2026-04-18 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_worker_workeraddrequest_workerauditlog'),
        ('issues', '0004_issue_completed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='assigned_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to='authentication.worker'),
        ),
    ]
